import "./globals.css";
import Header from "./components/header";

// Local fontu import et
import LocalFont from "next/font/local";

// Google fonts'daki fontu import etme
import { Playwrite_IT_Moderna } from "next/font/google";

// Google fonts'dan gelen fontu kurma
const playwrite = Playwrite_IT_Moderna({
  weight: "400",
  variable: "--playwrite",
});

// Local fontu kurma
export const kissing = LocalFont({
  src: "./assets/kissing.ttf",
  variable: "--kissing",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${playwrite.variable} ${kissing.variable} antialiased`}>
        <Header />

        <div className="min-h-screen text-2xl grid place-items-center font-semibold">{children}</div>
      </body>
    </html>
  );
}
